### ISSUE TITLE
ImportError: cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by sashigurram** [ljwolf/cenpy#18] opened 2018-03-01 14:54 UTC
Yesterday, I used cenpy in Python 3.6. However, to conform with the rest of our code I had to revert back to python 2.7. Now when I use cenpy, it gives me the following error. Do you have any work around apart from installing simplejson and calling the JSONDecodeError from it?

```
from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```

**Comment by ljwolf** [comment] 2018-03-01 15:17
This is a duplicate of #13. There are a few things Cenpy does that are python 3-only, and would have to be refactored to use in python 2. Further, there's [quite a bit of momentum to finally leave python 2](http://python3statement.org/).

I'm sorry... I know that doesn't really directly resolve your issue :(

**Closed by ljwolf** 2018-03-01 15:17 UTC
